# title: Continuous Delivery pipeline
# secrets: [ DOCKERHUB_USERNAME, DOCKERHUB_TOKEN ]
name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  image-push:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push container image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: devprofr/winsamplenet48svc
          platform: windows/amd64
          dockerfile: samples\dotnet-4.8\SampleWindowsService\Dockerfile
          directory: samples\dotnet-4.8
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: latest
